name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo check --all-features

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: cargo build
      - run: cargo build --features axum,ssr
      - run: cargo build --features actix,ssr
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-leptos
      - name: Build axum example
        working-directory: examples/axum-example
        run: cargo leptos build
      - name: Build actix-web example
        working-directory: examples/actix-example
        run: cargo leptos build

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all --check
